"""Added first_name to User

Revision ID: 82aa32e5bed4
Revises: c0b951151fa9
Create Date: 2023-01-21 17:11:29.280528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82aa32e5bed4'
down_revision = 'c0b951151fa9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
